name: drift_testcases
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  drift: ^2.22.1
  json_annotation: ^4.9.0
  test: ^1.25.8

dev_dependencies:
  build_runner: ^2.4.14
  drift_dev: ^2.22.1
  json_serializable: ^6.9.0
  lints: ^5.1.0
