name: legacy_web
description: Run integration tests for drift/web
publish_to: none
environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  drift: ^2.0.0
  drift_testcases:
    path: ../drift_testcases

dev_dependencies:
  test: ^1.24.0
  build_runner:
  build_web_compilers:
  drift_dev: ^2.0.0

dependency_overrides:
  drift:
    path: ../../../drift
  drift_dev:
    path: ../../../drift_dev
  sqlparser:
    path: ../../../sqlparser