name: sqlparser
description: Parses sqlite statements and performs static analysis on them
version: 0.40.0
homepage: https://github.com/simolus3/drift/tree/develop/sqlparser
repository: https://github.com/simolus3/drift
#homepage: https://drift.simonbinder.eu/
issue_tracker: https://github.com/simolus3/drift/issues

topics:
  - drift
  - database
  - sql

funding:
  - https://github.com/sponsors/simolus3

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  meta: ^1.15.0
  collection: ^1.19.0
  source_span: ^1.10.0
  charcode: ^1.4.0

dev_dependencies:
  lints: ^5.1.0
  test: ^1.25.8
  path: ^1.9.0
  ffi: ^2.1.3
  sqlite3: ^2.5.0
