name: benchmarks
description: Runs simple and complex benchmarks to measure performance of moor and moor_ffi

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  drift: ^2.22.1
  sqlite3: ^2.5.0
  benchmark_harness: ^2.3.1
  intl: ^0.20.1
  uuid: ^4.5.1
  path: ^1.9.0

dev_dependencies:
  build_runner: any
  drift_dev: ^2.22.1
  test: any

dependency_overrides:
  drift:
    path: ../../drift
  drift_dev:
    path: ../../drift_dev
  sqlparser:
    path: ../../sqlparser
