name: web_wasm
description: Integration tests for the drift wasm implementation
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  collection: ^1.19.0
  drift: any
  build_daemon: ^4.0.3
  webdriver: ^3.0.4
  shelf: ^1.4.2
  shelf_proxy: ^1.0.4
  path: ^1.9.0
  package_config: ^2.1.1
  async: ^2.11.0
  http: ^1.2.2
  sqlite3: ^2.5.0

dev_dependencies:
  build_runner: ^2.4.14
  build_web_compilers: ^4.1.0
  drift_dev: any
  lints: ^5.1.0
  test: ^1.25.8
