name: drift_dev
description: Dev-dependency for users of drift. Contains the generator and development tools.
version: 2.22.1
repository: https://github.com/simolus3/drift
homepage: https://drift.simonbinder.eu/
issue_tracker: https://github.com/simolus3/drift/issues

topics:
  - codegen
  - build-runner
  - drift
  - database

funding:
  - https://github.com/sponsors/simolus3

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  charcode: ^1.4.0
  collection: ^1.19.0
  recase: ^4.1.0
  meta: ^1.15.0
  path: ^1.9.0
  json_annotation: ^4.9.0
  stream_transform: ^2.1.1

  # CLI
  args: ^2.6.0
  logging: ^1.3.0
  cli_util: ^0.4.2
  yaml: ^3.1.2
  io: ^1.0.5

  # Drift-specific analysis and apis
  drift: ">=2.22.0 <2.23.0"
  sqlite3: ^2.5.0
  sqlparser: ^0.40.0

  # Dart analysis
  analyzer: ">=6.11.0 <8.0.0"
  source_span: ^1.10.0
  package_config: ^2.1.1
  pub_semver: ^2.1.5

  # Build system
  build: ^2.4.2
  build_resolvers: ^2.4.3
  build_config: ^1.1.2
  dart_style: ^3.0.0
  source_gen: ^2.0.0
  string_scanner: ^1.3.0

dev_dependencies:
  lints: ^5.1.0
  checked_yaml: ^2.0.3
  test: ^1.25.8
  test_descriptor: ^2.0.1
  build_runner: ^2.4.14
  build_test: ^2.2.3
  json_serializable: ^6.9.2
  crypto: ^3.0.6
  glob: ^2.1.2

executables:
  drift_dev:
