name: drift_mariadb
description: Mariadb support for drift.
version: 1.0.0

topics:
  - drift
  - database
  - mariadb

funding:
  - https://github.com/sponsors/simolus3

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  drift: ^2.22.1
  meta: ^1.15.0
  mysql_client: ^0.0.27

dev_dependencies:
  lints: ^5.1.0
  test: ^1.25.8
  drift_testcases:
    path: ../integration_tests/drift_testcases
