name: drift_devtools_extension
description: A Flutter web app contribution drift tools to DevTools
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  devtools_extensions: ^0.3.0
  devtools_app_shared: ^0.3.0
  db_viewer:
  drift_db_viewer:
  rxdart: ^0.28.0
  flutter_riverpod: ^3.0.0-dev.0
  vm_service: ^14.3.0
  path: ^1.9.0
  drift: ^2.22.1
  logging: ^1.3.0
  url_launcher: ^6.3.1
  drift_dev: ^2.22.1
  sqlite3: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  db_viewer:
    git:
      url: https://github.com/simolus3/db_viewer.git
      path: db_viewer
      ref: b1da96fc17f54e393d2781fef046d364f45220f0
  drift_db_viewer:
    git:
      url: https://github.com/simolus3/db_viewer.git
      path: drift_db_viewer
      ref: b1da96fc17f54e393d2781fef046d364f45220f0

flutter:
  uses-material-design: true
