name: flutter_db
description: Testing drift's `NativeDatabase` on Flutter.
version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  drift: ^2.22.1
  path: ^1.9.0
  sqlite3: ^2.5.0
  flutter:
    sdk: flutter
  drift_testcases:
    path: ../drift_testcases
  sqlite3_flutter_libs: ^0.5.28

dev_dependencies:
  test: ^1.25.8
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

dependency_overrides:
  drift:
    path: ../../../drift

flutter:
  assets:
    - test_asset.db
