name: encrypted_drift
description: Encryption support for drift, built with sqflite_sqlcipher
version: 1.0.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.22.1
  path: ^1.9.0
  sqflite_sqlcipher: ^3.1.0+1

dev_dependencies:
  drift_testcases:
    path: ../integration_tests/drift_testcases
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
