name: encrypted_drift
description: Encryption support for drift, built with sqflite_sqlcipher
version: 1.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.0.0
  path: ^1.8.1
  sqflite_sqlcipher: ^3.0.0

dev_dependencies:
  drift_testcases:
    path: ../integration_tests/drift_testcases
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
