name: drift_docs
description: Documentation website for the drift project.
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  drift:
  drift_postgres:
  path: ^1.9.0
  json_annotation: ^4.9.0
  # used in snippets
  http: ^1.2.2
  sqlite3: ^2.5.0

  # Used in examples
  rxdart: ^0.28.0
  yaml: ^3.1.2
  drift_dev: any
  test: ^1.25.8
  postgres: ^3.4.4
  uuid: ^4.5.1
  sqlcipher_flutter_libs: ^0.6.4
  sqlite3_flutter_libs: ^0.5.28
  path_provider: ^2.1.5
  drift_flutter: ^0.2.3

dev_dependencies:
  build_runner: ^2.4.14
  build_verify: ^3.1.0
  lints: ^5.1.0
  build: ^2.4.2
  build_web_compilers: ^4.1.0
  json_serializable: ^6.9.0
  source_span: ^1.10.0
  sqlparser: any
  characters: ^1.3.0
  args: ^2.6.0
  flutter_test:
    sdk: flutter
  webdev: ^3.7.0
  code_snippets:
    hosted: https://pub-simonbinder-eu.fsn1.your-objectstorage.com
    version: ^0.0.15
  sass_builder: ^2.2.1

dependency_overrides:
  drift_flutter:
    path: ../drift_flutter
  drift:
    path: ../drift
  drift_dev:
    path: ../drift_dev
  drift_postgres:
    path: ../extras/drift_postgres
  sqlparser:
    path: ../sqlparser

flutter:
  uses-material-design: true
